server {
    listen 80;

    location /api/auth {
        proxy_pass http://users-service:8000/auth;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/users {
        proxy_pass http://users-service:8000/users;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/books {
        proxy_pass http://books-service:8000/books;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/loans {
        proxy_pass http://loans-service:8000/loans;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        resolver 127.0.0.11 valid=10s;
        set $frontend_upstream http://frontend:80;
        proxy_pass $frontend_upstream;
        proxy_set_header Host $host;
    }
}
